# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en
  title: Academic
  params:
    description: Site
  menu:
    main:
      - name: Home
        url: '#about'
        weight: 10
      - name: Posts
        url: '#posts'
        weight: 20
      - name: Projects
        url: '#projects'
        weight: 30
      - name: Talks
        url: '#talks'
        weight: 40
      - name: Publications
        url: '#featured'
        weight: 50
      - name: Contact
        url: '#contact'
        weight: 60
        

# Uncomment the lines below to configure your website in a second language.
ru:
  languageCode: ru-ru
  contentDir: content/ru
  title: Академик
  params:
    description: Сайт
  menu:
    main:
      - name: Главная
        url: '#about'
        weight: 10
      - name: Посты
        url: '#posts'
        weight: 20
      - name: Проекты
        url: '#projects'
        weight: 30
      - name: Разговоры
        url: '#talks'
        weight: 40
      - name: Публикации
        url: '#featured'
        weight: 50
      - name: Контакты
        url: '#contact'
        weight: 60
